language: node_js

node_js:
  - stable

install:
  - npm install

env:
  global:
    - secure: "CZKvcY7aJYMQwyH5sOczvbVZDTX5TtkSHNfSAcZgkUWzTwp603FniMO3EBiYg95vsmYDcq5e1Ql13luGy7Dsgb8qMcCuUR4ECkocIkyobk4tcPasm/BSqffvRcXIs576Ozp+E3LZU7bb0gJ9+W3safqZsW1ipaO5b0PBnsA0ojZwRMgv982SpaPY7/z7f2hVYF1Uc1g1JyCeqTo4Y/o4C4nehWnyHMMGpr2CocPtWrKuR/7UIWCGQUTXN0yU4lyP17cMJqyTKHMv8A8DVd9OzYgfQqRYdxuECe21e1PVcguqSYmKLh8g79oTCZ8GGIfHxM53rN96IjjrtTpngGBoxwHwkJODSQqgqvBI6qHfwztnKNC+rMHMe8XWmKGSzWwL6s4jWl0enTJ0NgqvuKkMja2S9fzoc8mCrakcBoNPT5Mgc8alCXvz8TIS0MW3rPZtBT7oRyNl5Sl5hrNOrOhuVgvJw/yFQhJPIUsoM+/S6VzVvCM9fqHwbg7OO7F2UhF+H3sj/7i6aczOVdGsFsUkD1bf2SJalEPyZDhEYavsaBs5vKeIAkX3anpDDaiq8DIzc2YLjp4F2Oe3IcnzKPFQU/ZZlNuYzLSoedEqDcVfCDcvnIrMsdaxE6JioCla8AqU7vMEZ5n+y2mZbkrybWLOTdzTnC/jtDZ3DUCpcZ284bk="

script:
  - npm run lint
  - npm run test:unit
  - npm run build
